Refs: \
https://pytorch.org/docs/stable/tensors.html \
https://jovian.ai/aakashns/01-pytorch-basics \
https://www.youtube.com/watch?v=GIsg-ZUy0MY \
https://www.youtube.com/watch?v=exaWOE8jvy8

In [2]:
import numpy as np
import torch

### Creating a tensor
A tensor is a number, vector, matrix or any n-dimensional array.

In [52]:
# number
t1 = torch.tensor(2.)
t1

tensor(2.)

In [51]:
# vector
t2 = torch.tensor([1., 2, 5, 8.])
t2

tensor([1., 2., 5., 8.])

In [50]:
# matrix
t3 = torch.tensor([[11,12, 13], [21, 22, 23]])
t3

tensor([[11, 12, 13],
        [21, 22, 23]])

In [3]:
x = torch.empty(1)
print(x)

tensor([0.])


In [4]:
x = torch.empty(3)
print(x)

tensor([ 0.0000e+00, -2.5244e-29,  1.4329e+10])


In [5]:
x = torch.empty(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.rand(3,2)
x

tensor([[0.2111, 0.2224],
        [0.4734, 0.0069],
        [0.6136, 0.6834]])

In [7]:
# create a one-dimensional tensor of size 3:
x = torch.ones(3)
x

tensor([1., 1., 1.])

In [8]:
x = torch.ones(3,2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [9]:
x = torch.ones(3,2, dtype=torch.int32)
x

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

In [10]:
x.size()

torch.Size([3, 2])

In [11]:
x.shape

torch.Size([3, 2])

In [12]:
x = torch.tensor([[11, 12], [21, 22], [31, 32]])
x

tensor([[11, 12],
        [21, 22],
        [31, 32]])

In [13]:
x[:2,:]

tensor([[11, 12],
        [21, 22]])

In [14]:
x[:,1]

tensor([12, 22, 32])

In [15]:
x[0,1]

tensor(12)

In [16]:
x[0,1].item()

12

### Operations

In [17]:
x = torch.tensor(2.)
print(x)

y = x + 100
print(y)

tensor(2.)
tensor(102.)


In [18]:
x = torch.ones(3)
print(x)

x[2] = 3.
print(x)

tensor([1., 1., 1.])
tensor([1., 1., 3.])


In [19]:
x = torch.tensor([[11, 12], [21, 22]])
print(x)

y = x + 100
print(y)

tensor([[11, 12],
        [21, 22]])
tensor([[111, 112],
        [121, 122]])


In [20]:
## addition
x = torch.tensor([[11, 12], [21, 22]])
print(x)

y = torch.tensor([[1000, 2000], [3000, 4000]])
print(y)

z = x + y
print(z)

tensor([[11, 12],
        [21, 22]])
tensor([[1000, 2000],
        [3000, 4000]])
tensor([[1011, 2012],
        [3021, 4022]])


In [21]:
## element multiplication
x = torch.tensor([[11, 12], [21, 22]])
print(x)

y = torch.tensor([[1000, 2000], [3000, 4000]])
print(y)

z = x * y
print(z)

tensor([[11, 12],
        [21, 22]])
tensor([[1000, 2000],
        [3000, 4000]])
tensor([[11000, 24000],
        [63000, 88000]])


In [22]:
## element division
x = torch.tensor([[10, 100], [20, 200]])
print(x)

y = torch.tensor([[1000, 2000], [3000, 4000]])
print(y)

z = y / x
print(z)

tensor([[ 10, 100],
        [ 20, 200]])
tensor([[1000, 2000],
        [3000, 4000]])
tensor([[100.,  20.],
        [150.,  20.]])


In [23]:
## reshape
x = torch.tensor([[11, 12], [21, 22], [31, 32]])
print(x)

x1 = x.reshape(2,3)
print(x1)

x2 = x.reshape(-1,)
print(x2)

tensor([[11, 12],
        [21, 22],
        [31, 32]])
tensor([[11, 12, 21],
        [22, 31, 32]])
tensor([11, 12, 21, 22, 31, 32])


In [24]:
## 2D transpose
x = torch.tensor([[11, 12], [21, 22], [31, 32]])
print(x, x.shape)

y = x.t() 
print(y, y.shape)

tensor([[11, 12],
        [21, 22],
        [31, 32]]) torch.Size([3, 2])
tensor([[11, 21, 31],
        [12, 22, 32]]) torch.Size([2, 3])


In [25]:
## for higher transpose, need to specify the two dimensions
x = torch.tensor([[[11,12,13, 14], [21,22,23,24], [31,32,33,34]],
                  [[101,102,103, 104], [201,202,203,204], [301,302,303,304]]])
print(x, x.shape)

y = x.transpose(0,2) 
print(y, y.shape)

tensor([[[ 11,  12,  13,  14],
         [ 21,  22,  23,  24],
         [ 31,  32,  33,  34]],

        [[101, 102, 103, 104],
         [201, 202, 203, 204],
         [301, 302, 303, 304]]]) torch.Size([2, 3, 4])
tensor([[[ 11, 101],
         [ 21, 201],
         [ 31, 301]],

        [[ 12, 102],
         [ 22, 202],
         [ 32, 302]],

        [[ 13, 103],
         [ 23, 203],
         [ 33, 303]],

        [[ 14, 104],
         [ 24, 204],
         [ 34, 304]]]) torch.Size([4, 3, 2])


In [26]:
## covert tensor to plain Python
x = torch.tensor([11,12,13,16])
print(x)

print(x[1])

print(float(x[1]))

tensor([11, 12, 13, 16])
tensor(12)
12.0


In [27]:
## convert torch to numpy
x = torch.tensor([[11, 12], [21, 22], [31, 32]])
print(x)

y = x.numpy()
print(y)
print(type(y))

z = np.array(x)
print(z)
print(type(z))

tensor([[11, 12],
        [21, 22],
        [31, 32]])
[[11 12]
 [21 22]
 [31 32]]
<class 'numpy.ndarray'>
[[11 12]
 [21 22]
 [31 32]]
<class 'numpy.ndarray'>


In [28]:
## convert numpy to torch
x = np.array([[11, 12], [21, 22], [31, 32]])
print(x)

y = torch.from_numpy(x)
print(y)

print('  ')
x += 100
print(x)

print(y)

[[11 12]
 [21 22]
 [31 32]]
tensor([[11, 12],
        [21, 22],
        [31, 32]])
  
[[111 112]
 [121 122]
 [131 132]]
tensor([[111, 112],
        [121, 122],
        [131, 132]])


### Shape of image tensors

In [29]:
## 3D tensor for image: [channels, rows, columns]
img_t = torch.randn(3,5,5)  # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [30]:
## with bathch_t: batch_t = 2 for instance
batch_t = torch.randn(2,3,5,5)  # shape [batch, channels, rows, columns]

In [31]:
batch_t

tensor([[[[-3.2108e-01,  1.3435e-01, -5.1875e-01, -8.2088e-01, -1.5634e+00],
          [-1.7870e-01, -3.3559e-01,  1.2007e-01, -1.3797e+00, -1.1352e+00],
          [ 4.4099e-01,  1.5231e+00, -1.2819e-01,  1.8978e-01, -1.0727e+00],
          [-3.1410e-01, -1.5475e+00,  1.1043e+00, -4.8423e-01,  2.8692e-01],
          [-1.1729e+00, -2.2115e+00, -4.4963e-01, -2.2801e+00,  1.8238e-01]],

         [[-9.9248e-01, -6.9789e-02, -5.5713e-01, -1.3315e-03, -3.8328e-01],
          [-1.8814e-01, -1.8258e+00, -2.7561e-01, -4.4539e-01, -1.1003e+00],
          [ 3.1505e-01, -2.6726e-01,  2.3241e-01, -3.8361e-01, -1.4943e+00],
          [-8.2953e-01,  9.1905e-02,  1.0462e+00, -1.1005e+00, -7.6292e-01],
          [-1.2825e-01,  4.4365e-01,  1.3688e+00,  5.6648e-01, -1.1249e+00]],

         [[-1.0681e+00, -1.7074e+00, -3.2214e-01, -1.3174e-01, -2.3485e-01],
          [ 7.6626e-01,  1.4221e+00, -1.2236e+00, -8.1489e-01, -3.6494e-01],
          [ 5.7969e-01,  5.8682e-01, -1.5262e+00,  1.3709e+00,  4.4790e-

In [32]:
batch_t.shape

torch.Size([2, 3, 5, 5])

### Multiplication

In [33]:
## So sometimes the RBG channels are in dimension 0, and sometimes they are in dimension 1. 
## But they are always the 3rd from the end -- dimension -3. So the unweighted mean can be calculated:

img_gray_native = img_t.mean(-3)

batch_gray_native = batch_t.mean(-3)

img_gray_native.shape, batch_gray_native.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [34]:
## With weights, PyTorch allows to multiply tensors of the same shape, as well as shapes where 
## one operand is of size 1 in a given dimension: (2,3,5,5) x (3,1,1) --> (2,3,5,5)

print(weights.shape)
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
print(unsqueezed_weights.shape)

torch.Size([3])
torch.Size([3, 1, 1])


In [35]:
print(img_t.shape)

img_weights = (img_t * unsqueezed_weights)

print(img_weights.shape)

torch.Size([3, 5, 5])
torch.Size([3, 5, 5])


In [36]:
print(batch_t.shape)

batch_weights = (batch_t * unsqueezed_weights)

print(batch_weights.shape)

torch.Size([2, 3, 5, 5])
torch.Size([2, 3, 5, 5])


In [37]:
img_gray_weighted = img_weights.sum(-3)
print(img_gray_weighted.shape)

torch.Size([5, 5])


In [38]:
batch_gray_weighted = batch_weights.sum(-3)
print(batch_gray_weighted.shape)

torch.Size([2, 5, 5])


#### Einsum

In [39]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)

print(batch_gray_weighted_fancy.shape)

torch.Size([2, 5, 5])


### Named tensors

In [40]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/Users/u1094325/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:848.)
  """Entry point for launching an IPython kernel.


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [41]:
## Use `refine_names` to add names to a tensor (but not change existing ones):
print(img_t.shape)

img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns') 
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

torch.Size([3, 5, 5])
img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [42]:
## align_as: aligns dimensions, returns a tensor with missing dimensions added:
print(img_named.shape, img_named.names)
print(weights_named.shape, weights_named.names)

weights_aligned = weights_named.align_as(img_named) 

print(weights_aligned.shape, weights_aligned.names)

torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
torch.Size([3]) ('channels',)
torch.Size([3, 1, 1]) ('channels', 'rows', 'columns')


In [43]:
gray_named = (img_named * weights_aligned).sum('channels')

print(gray_named.shape, gray_named.names)

torch.Size([5, 5]) ('rows', 'columns')


In [44]:
gray_named = (img_named * weights_aligned).sum(axis=0)

print(gray_named.shape, gray_named.names)

torch.Size([5, 5]) ('rows', 'columns')


In [45]:
## drop names
gray_plain = gray_named.rename(None)

print(gray_plain.shape, gray_plain.names)

torch.Size([5, 5]) (None, None)
