Refs:

https://github.com/deep-learning-with-pytorch/dlwpt-code

In [1]:
import numpy as np
import torch
import torch.optim as optim
import torch.nn as nn

### Build a linear model from the torch.nn package

In [2]:
x = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
y = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]

x = torch.tensor(x)
y = torch.tensor(y)

## normalize:
x = 0.1*x   

In [3]:
x

tensor([3.5700, 5.5900, 5.8200, 8.1900, 5.6300, 4.8900, 3.3900, 2.1800, 4.8400,
        6.0400, 6.8400])

In [4]:
x.shape

torch.Size([11])

In [5]:
x = x.reshape((-1,1))
y = y.reshape((-1,1))

print(x.shape, y.shape)

torch.Size([11, 1]) torch.Size([11, 1])


In [6]:
## Splitting the dataset
n_samples = x.shape[0]
n_val = int(0.2 * n_samples)

i_shuffled = torch.randperm(n_samples)

i_train = i_shuffled[:-n_val]
i_val = i_shuffled[-n_val:]

i_train, i_val

x_train = x[i_train]
y_train = y[i_train]

x_val = x[i_val]
y_val = y[i_val]

In [7]:
def training_loop(n_epochs, optimizer, model, loss_fn, x_train, y_train, x_val, y_val):
    for epoch in range(1, n_epochs + 1):
        y_train_p = model(x_train)
        loss_train = loss_fn(y_train_p, y_train)
                             
        y_val_p = model(x_val)
        loss_val = loss_fn(y_val_p, y_val)
        
        optimizer.zero_grad()
        loss_train.backward()
        optimizer.step()

        if epoch <= 3 or epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {loss_train.item():.4f},"
                  f" Validation loss {loss_val.item():.4f}")


In [8]:
model = nn.Linear(1, 1) ## 1 input and 1 output
loss_fn = nn.MSELoss()

learning_rate = 1e-2
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

training_loop(n_epochs = 3000, optimizer = optimizer, model = model, loss_fn = loss_fn,
              x_train = x_train, y_train = y_train, x_val = x_val, y_val = y_val)

Epoch 1, Training loss 136.3586, Validation loss 15.8594
Epoch 2, Training loss 47.2446, Validation loss 4.1492
Epoch 3, Training loss 35.0512, Validation loss 15.9298
Epoch 500, Training loss 6.8037, Validation loss 11.7019
Epoch 1000, Training loss 3.1078, Validation loss 7.6823
Epoch 1500, Training loss 2.5966, Validation loss 6.4182
Epoch 2000, Training loss 2.5259, Validation loss 5.9800
Epoch 2500, Training loss 2.5161, Validation loss 5.8215
Epoch 3000, Training loss 2.5147, Validation loss 5.7631


In [9]:
model.weight

Parameter containing:
tensor([[5.3087]], requires_grad=True)

In [10]:
model.bias

Parameter containing:
tensor([-16.5881], requires_grad=True)