Refs: \
https://pytorch.org/docs/stable/tensors.html \
https://jovian.ai/aakashns/01-pytorch-basics \
https://www.youtube.com/watch?v=GIsg-ZUy0MY \
https://www.youtube.com/watch?v=exaWOE8jvy8

In [53]:
import numpy as np
import torch

### Creating a tensor

In [34]:
x = torch.empty(1)
print(x)

tensor([7.0065e-45])


In [35]:
x = torch.empty(3)
print(x)

tensor([ 0.0000e+00, -8.5899e+09,  0.0000e+00])


In [36]:
x = torch.empty(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [37]:
x = torch.rand(3,2)
x

tensor([[0.0258, 0.9998],
        [0.8737, 0.8037],
        [0.5928, 0.7908]])

In [38]:
x = torch.ones(3,2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [39]:
x = torch.ones(3,2, dtype=torch.int32)
x

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

In [40]:
x.size()

torch.Size([3, 2])

In [41]:
x.shape

torch.Size([3, 2])

In [42]:
x = torch.tensor([[11, 12], [21, 22], [31, 32]])
x

tensor([[11, 12],
        [21, 22],
        [31, 32]])

In [43]:
x[:2,:]

tensor([[11, 12],
        [21, 22]])

In [44]:
x[:,1]

tensor([12, 22, 32])

In [45]:
x[0,1]

tensor(12)

In [47]:
x[0,1].item()

12

### Operations

In [24]:
x = torch.tensor(2.)
print(x)

y = x + 100
print(y)

tensor(2.)
tensor(102.)


In [23]:
x = torch.tensor([[11, 12], [21, 22]])
print(x)

y = x + 100
print(y)

tensor([[11, 12],
        [21, 22]])
tensor([[111, 112],
        [121, 122]])


In [25]:
## addition
x = torch.tensor([[11, 12], [21, 22]])
print(x)

y = torch.tensor([[1000, 2000], [3000, 4000]])
print(y)

z = x + y
print(z)

tensor([[11, 12],
        [21, 22]])
tensor([[1000, 2000],
        [3000, 4000]])
tensor([[1011, 2012],
        [3021, 4022]])


In [26]:
## element multiplication
x = torch.tensor([[11, 12], [21, 22]])
print(x)

y = torch.tensor([[1000, 2000], [3000, 4000]])
print(y)

z = x * y
print(z)

tensor([[11, 12],
        [21, 22]])
tensor([[1000, 2000],
        [3000, 4000]])
tensor([[11000, 24000],
        [63000, 88000]])


In [31]:
## element division
x = torch.tensor([[10, 100], [20, 200]])
print(x)

y = torch.tensor([[1000, 2000], [3000, 4000]])
print(y)

z = y / x
print(z)

tensor([[ 10, 100],
        [ 20, 200]])
tensor([[1000, 2000],
        [3000, 4000]])
tensor([[100.,  20.],
        [150.,  20.]])


In [50]:
## reshape
x = torch.tensor([[11, 12], [21, 22], [31, 32]])
print(x)

x1 = x.reshape(2,3)
print(x1)

x2 = x.reshape(-1,)
print(x2)

tensor([[11, 12],
        [21, 22],
        [31, 32]])
tensor([[11, 12, 21],
        [22, 31, 32]])
tensor([11, 12, 21, 22, 31, 32])


In [58]:
## convert torch to numpy
x = torch.tensor([[11, 12], [21, 22], [31, 32]])
print(x)

y = x.numpy()
print(y)
print(type(y))

z = np.array(x)
print(z)
print(type(z))

tensor([[11, 12],
        [21, 22],
        [31, 32]])
[[11 12]
 [21 22]
 [31 32]]
<class 'numpy.ndarray'>
[[11 12]
 [21 22]
 [31 32]]
<class 'numpy.ndarray'>


In [60]:
## convert numpy to torch
x = np.array([[11, 12], [21, 22], [31, 32]])
print(x)

y = torch.from_numpy(x)
print(y)

print('  ')
x += 100
print(x)

print(y)

[[11 12]
 [21 22]
 [31 32]]
tensor([[11, 12],
        [21, 22],
        [31, 32]])
  
[[111 112]
 [121 122]
 [131 132]]
tensor([[111, 112],
        [121, 122],
        [131, 132]])
