Credits: \
https://pytorch.org/docs/stable/tensors.html \
https://jovian.ai/aakashns/01-pytorch-basics \
https://www.youtube.com/watch?v=GIsg-ZUy0MY

In [1]:
import torch

### Tensors
A tensor is a number, vector, matrix or any n-dimensional array.

In [2]:
# number
t1 = torch.tensor(2.)
t1

tensor(2.)

In [3]:
t1.dtype

torch.float32

In [4]:
# vector
t2 = torch.tensor([1., 2, 5, 8.])
t2

tensor([1., 2., 5., 8.])

In [5]:
# matrix
t3 = torch.tensor([[11,12, 13], [21, 22, 23]])
t3

tensor([[11, 12, 13],
        [21, 22, 23]])

In [6]:
t3.shape

torch.Size([2, 3])

In [7]:
t3.shape[0]

2

In [8]:
len(t2)

4

### Tensor operations and gradients

In [9]:
# Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

We've created 3 tensors `x`, `w` and `b`, all numbers. `w` and `b` have an additional parameter requires_grad set to `True`. We'll see what it does in just a moment.

Let's create a new tensor `y` by combining these tensors:

In [10]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch special is that we can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to True i.e. `w` and `b`. To compute the derivatives, we can call the `.backward` method on our result `y`.

In [11]:
# Compute derivatives
y.backward()

The derivates of `y` w.r.t the input tensors are stored in the `.grad` property of the respective tensors.

In [12]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


### Interoperability with Numpy

In [13]:
import numpy as np

x = np.array([[11, 12, 13], [21, 22., 23]])
x

array([[11., 12., 13.],
       [21., 22., 23.]])

In [14]:
# convert a Numpy array to a PyTorch tensor using torch.from_numpy
y = torch.from_numpy(x)  # doesn't create a copy of x
y

tensor([[11., 12., 13.],
        [21., 22., 23.]], dtype=torch.float64)

In [15]:
x.dtype

dtype('float64')

In [16]:
y.dtype

torch.float64

In [17]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[11., 12., 13.],
       [21., 22., 23.]])

In [18]:
y = torch.tensor(x)  # create a copy of x
y

tensor([[11., 12., 13.],
        [21., 22., 23.]], dtype=torch.float64)